version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pylerchart
    image: yknam/pylerchart
    volumes:
      - ./src:/app/src
    ports:
      - "15009:80"
